name: Deploy to GitHub Pages

on:
  push:
    branches:
      - ci-web

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Download
        uses: actions/checkout@v4

      - name: Build website
        run: mkdir ./docs/_site; python ./docs/xml-to-html.py

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs/_site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
